version: '2'

networks:
  sadeem:
    external: true

services:
  smdb:
    container_name: smdb
    image: sadeem/smdb:v1.0
    restart: always
    networks:
      - sadeem
    ports:
      - '8022:8022'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/smdb
      - /home/smdb/node_modules
      - .env:/home/smdb/.env
      - ./logs:/home/smdb/logs
      - ./public:/home/smdb/public
      - ./private:/home/smdb/private
      - ./json_google:/home/smdb/json_google
